# Generated by Django 4.2.6 on 2023-11-03 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_livromodel_ano_alter_livromodel_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livromodel',
            name='ano',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='livromodel',
            name='isbn',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='livromodel',
            name='paginas',
            field=models.IntegerField(null=True),
        ),
    ]
